In [3]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F
import os 
from models.unet import UNet


In [73]:
model = UNet(n_class = 1)
model.load_state_dict(torch.load('trained_model/unet_midv_4.pt'))
model = nn.Sequential(model, nn.Sigmoid())

model.cuda()

Sequential(
  (0): UNet(
    (dconv1): Sequential(
      (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU(inplace=True)
      (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU(inplace=True)
    )
    (dconv2): Sequential(
      (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU(inplace=True)
      (2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU(inplace=True)
    )
    (dconv3): Sequential(
      (0): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU(inplace=True)
      (2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU(inplace=True)
    )
    (dconv4): Sequential(
      (0): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU(inplace=True)
      (2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU(i

In [74]:
model.eval()

Sequential(
  (0): UNet(
    (dconv1): Sequential(
      (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU(inplace=True)
      (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU(inplace=True)
    )
    (dconv2): Sequential(
      (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU(inplace=True)
      (2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU(inplace=True)
    )
    (dconv3): Sequential(
      (0): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU(inplace=True)
      (2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU(inplace=True)
    )
    (dconv4): Sequential(
      (0): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU(inplace=True)
      (2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU(i

In [37]:
torch.cuda.empty_cache()

In [58]:
import albumentations

In [60]:
transform = albumentations.Compose( [albumentations.LongestMaxSize(max_size=512, p=1)], p=1  )

In [61]:
transform(image)

AssertionError: force_apply must have bool or int type

In [63]:
# example images 

import cv2 

image = cv2.imread('data_processed/images/CA12_07.jpg')
image = cv2.resize(image, (512, 512))

In [72]:
output = model(torch.from_numpy(image).unsqueeze(0).view(1, 3, 512, 512).float().cuda())

RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 5.93 GiB total capacity; 5.32 GiB already allocated; 63.50 MiB free; 5.40 GiB reserved in total by PyTorch)

In [68]:
output

tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]]], device='cuda:0',
       grad_fn=<SigmoidBackward>)

In [65]:
import numpy as np 

In [66]:
np.min(output.squeeze(0).cpu().detach().numpy())

1.0

In [67]:
output

tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]]], device='cuda:0',
       grad_fn=<SigmoidBackward>)

In [34]:
import numpy as np 

In [ ]:
import matplotlib.pyplot as plt

In [45]:
_image= output.squeeze(0)

In [46]:
_image

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]], device='cuda:0',
       grad_fn=<SqueezeBackward1>)

In [47]:

mask = (label > 0).astype(np.uint8)

NameError: name 'label' is not defined

In [ ]:
torch.unsqueeze(torch.from_numpy(mask), 0).float()